services:
  - type: web
    name: agenciabase
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install --include=dev && npm run build
    startCommand: node server.cjs
    envVars:
      - key: NODE_VERSION
        value: 20
    autoDeploy: true
